name: cpp-ci

on:
  pull_request:
    paths:
      - "!docs/**"
      - "!README.md"
  push:
    paths:
      - "!docs/**"
      - "!README.md"

jobs:
  cpp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create build directory
        run: |
          cd mycpppkg/test
          mkdir build

      - name: Download GoogleTest and build test
        run: |
          cd mycpppkg/test/build
          cmake ..
          cmake --build .

      - name: Run test
        run: ./mycpppkg/test/build/module_test
