name: private-repo

on:
  push:
    branches:
      - master
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GIT_SSH_COMMAND: ssh -i ~/personal_token
        run: |
          echo "$PERSONAL_TOKEN" > ~/personal_token
          chmod 600 ~/personal_token
          git clone git@github.com:ktro2828/LittleSLAM-practice
          ls LittleSLAM-practice/
