name: python-ci

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  python-ci:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.7.11", "3.8", "3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies and run test
        run: |
          if [ -e requirements.txt ]; then
            python -m pip install -U pip
            python -m pip install setuptools
            python -m pip install -r requirements.txt --no-cache-dir
            python -m unittest discover
          fi

          if [ -e pyproject.toml ]; then
            sudo apt-get update
            sudo apt-get install curl
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            echo "$HOME/.poetry/bin" >> $GITHUB_PATH
            source $HOME/.poetry/env
            poetry install
            cd mypypkg
            poetry run python3 -m unittest discover
          fi
